services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - store:/qdrant/storage:z
  ollama:
    image: ollama/ollama
    container_name: ollama
    pull_policy: always
    tty: true
    ports:
      - 11434:11434
    volumes:
        - ollama:/root/.ollama
  server:
    container_name: server
    build: .
    ports:
      - 3001:3001
    depends_on:
      - qdrant
      - ollama
    volumes:
      - ./data:/data

volumes:
  ollama:
    driver: local
  store:
    driver: local
