services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - store:/qdrant/storage:z

volumes:
  store:
    driver: local
